---
# tasks file for hdfs
- name: install {{ hdfs_daemon }}
  yum:
    name: "{{ hdfs_daemon_name }}"
    state: present

- name: distribute {{ hdfs_daemon }} defaults file
  template:
    src: etc-default-hadoop-hdfs-{{ hdfs_daemon }}.j2
    dest: /etc/default/{{ hdfs_daemon_name }}
    owner: root
    group: root
    mode: 0644

- name: copy out {{ hdfs_daemon }} service file
  template:
    src: hadoop-hdfs-daemon.service.j2
    dest: /etc/systemd/system/{{ hdfs_daemon_name }}.service
    owner: root
    group: root
    mode: 0644

- name: explicitly stop/disable {{ hdfs_daemon }}
  systemd:
    name: "{{ hdfs_daemon_name }}"
    state: stopped
    enabled: no
